tabs:
  main:
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
          -
            handle: product_variants
            field:
              type: product_variants
              handle: product_variants
              width: 100
              option_fields:
                -
                  handle: downloadable_asset
                  field:
                    type: assets
                    mode: grid
                    display: 'Downloadable Asset'
                    container: assets
                    if:
                      root.product_type: 'equals digital'
                -
                  handle: download_limit
                  field:
                    type: integer
                    display: 'Download Limit'
                    instructions: "If you'd like to limit the amount if times this product can be downloaded, set it here. Keep it blank if you'd like it to be unlimited."
                    if:
                      root.product_type: 'equals digital'
  sidebar:
    sections:
      -
        fields:
          -
            handle: product_type
            field:
              type: button_group
              display: 'Product Type'
              options:
                physical: Physical
                digital: Digital
              default: physical
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: tax_category
            field:
              type: tax_category
              display: 'Tax Category'
              max_items: 1
              mode: select
