title: Product
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              width: 50
          -
            handle: price
            field:
              type: money
              display: Price
              save_zero_value: true
              listable: hidden
              width: 50
              instructions_position: above
              visibility: visible
              always_save: false
              validate:
                - required
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: product_type
            field:
              type: button_group
              display: 'Product Type'
              options:
                physical: Physical
                digital: Digital
              default: physical
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate:
                - required
      -
        display: 'Digital Product'
        fields:
          -
            handle: downloadable_asset
            field:
              type: assets
              mode: grid
              display: 'Downloadable Asset'
              container: assets
              if:
                root.product_type: 'equals digital'
          -
            handle: download_limit
            field:
              type: integer
              display: 'Download Limit'
              instructions: "If you'd like to limit the amount if times this product can be downloaded, set it here. Keep it blank if you'd like it to be unlimited."
              if:
                root.product_type: 'equals digital'
